version: '3.4'

volumes:
  l2_data:


services:
  morph-geth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303"
    volumes:
      - "${PWD}/db:/db"
      - "${PWD}/build/jwt-secret.txt:/config/jwt-secret.txt"
      - "${PWD}/genesis_l2.json:/genesis.json"
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"
      - "--authrpc.jwtsecret=/config/test-jwt-secret.txt"

